### ISSUE TITLE
Unexpected behavior of dfa.minimize method

### ISSUE THREAD

**Issue by vladistan** [whitemech/pythomata#15] opened 2018-04-14 02:11 UTC
* Pythomata version:  clone from master commit id b42e5e3f012
* Python version:  CPython 3.5.3
* Operating System: MacOS

### Description

Unexpected behavior of dfa.minimize function
( Am I not understanding it right )

### What I Did

I have a DFA automata like this:

![image](https://user-images.githubusercontent.com/36257/38763298-786630d4-3f4d-11e8-9d7e-52b9d806429b.png)

Let's call it  *dfa1*

I call the following function on it

dfa3 = dfa2.minimize()

And I end up with this

![image](https://user-images.githubusercontent.com/36257/38763308-cb0ec0bc-3f4d-11e8-88c0-bc5b4ea40293.png)

Questions:

     - Why there are transitions coming from state 2 on the same symbols.  There is transition on symbol 'E' that  leads both state 2 and state 1

     - The minimized automata will accept words that original automate will not accept, because the order of sequence of states is lost.   Dfa2 will only accept single word 'HELO'   DFa3 will also accept words 'HHO'  'ELLHO' etc... basically [HEL]+O

**Comment by MarcoFavorito** [comment] 2018-04-14 12:15
Hi @vladistan,
thank you for your report. I fixed some bugs and committed on the master branch. Please retrieve the changes.
But maybe the problem is still not solved for you. I tried to build the same automaton you described in [this test](https://github.com/MarcoFavorito/pythomata/blob/master/tests/test_dfa.py#L110-L132), so you can run yourself the code just by running the tests.

The next image is the output after executing `dfa.minimize().to_dot()`.
![image](https://user-images.githubusercontent.com/9467617/38768058-12a23b66-3fee-11e8-8f83-8b888aa4290e.png)

Can you post your code here? So your issue can be reproduced. Thank you :-)

**Closed** 2020-02-09 22:03 UTC
Labels: help wanted
